inicio/urls.py
from django.urls import path
from inicio import views

app_name = 'inicio'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('gatos/crear/', views.crear_gato, name='crear_gato'),
    path('gatos/', views.listar_gatos, name='gatos'),
    path('gatos/<int:pk>/', views.DetalleGato.as_view(), name='detalle_gato'),
    path('gatos/<int:pk>/modificar/', views.ModificarGato.as_view(), name='modificar_gato'),
    path('gatos/<int:pk>/eliminar/', views.EliminarGato.as_view(), name='eliminar_gato'),
]

repaso/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('inicio.urls')),
    path('admin/', admin.site.urls),
]

inicio/models.py
from django.db import models

# Create your models here.

class Gato(models.Model):
    nombre = models.CharField(max_length=20)
    edad = models.IntegerField()
    fecha_nacimiento = models.DateField(null=True)
    
    def __str__(self):
        return f'Nombre: {self.nombre} - Edad: {self.edad}'

inicio/forms.py
from django import forms

class CrearGatoFormulario(forms.Form):
    nombre = forms.CharField(max_length=20)
    edad = forms.IntegerField()
    fecha_nacimiento = forms.DateField(required=False, widget=forms.DateInput(format='%d/%m/%Y'), input_formats=('%d/%m/%Y', ))
    
    
class BusquedaGatoFormulario(forms.Form):
    nombre = forms.CharField(max_length=20, required=False)

inicio/views.py
from django.shortcuts import render
from inicio.forms import CrearGatoFormulario, BusquedaGatoFormulario
from inicio.models import Gato

from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic.detail import DetailView

from django.urls import reverse_lazy


# Create your views here.

def inicio(request):
    return render(request, 'inicio/inicio.html')

def crear_gato(request):
    mensaje = ''
    
    if request.method == 'POST':
        formulario = CrearGatoFormulario(request.POST)
        if formulario.is_valid():
            info = formulario.cleaned_data
            gato = Gato(nombre=info['nombre'],edad=info['edad'],fecha_nacimiento=info['fecha_nacimiento'])
            gato.save()
            mensaje = f'Se creo el gato {gato.nombre}'
        else:
            return render(request, 'inicio/crear_gato.html', {'formulario': formulario})
    
    formulario = CrearGatoFormulario()
    return render(request, 'inicio/crear_gato.html', {'formulario': formulario, 'mensaje': mensaje})

def listar_gatos(request):
    
    formulario = BusquedaGatoFormulario(request.GET)
    if formulario.is_valid():
        nombre_a_buscar = formulario.cleaned_data.get('nombre', '')
        lista_gatos = Gato.objects.filter(nombre__icontains=nombre_a_buscar)
    
    formulario = BusquedaGatoFormulario()
    return render(request, 'inicio/gatos.html', {'formulario': formulario, 'lista_gatos': lista_gatos})


class DetalleGato(DetailView):
    model = Gato
    template_name = "inicio/detalle_gato.html"


class ModificarGato(UpdateView):
    model = Gato
    fields = ['nombre', 'edad', 'fecha_nacimiento']
    template_name = "inicio/modificar_gato.html"
    success_url = reverse_lazy('inicio:gatos')


class EliminarGato(DeleteView):
    model = Gato
    template_name = "inicio/eliminar_gato.html"
    success_url = reverse_lazy('inicio:gatos')

inicio/templates/inicio/crear_gato.html
{% extends 'base.html' %}

{% block title_head %}
<title>Crear Gato</title>
{% endblock title_head %}

{% block h1_header %}
Crear Gato
{% endblock h1_header %}

{% block contenido %}

<p>{{mensaje}}</p>

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Crear</button>
</form>

{% endblock contenido %}

inicio/templates/inicio/detalle_gato.html
{% extends 'base.html' %}

{% block title_head %}
<title>Gato</title>
{% endblock title_head %}

{% block h1_header %}
Datos del gato {{gato.nombre}}
{% endblock h1_header %}

{% block contenido %}
<li>Edad: {{gato.edad}}</li>
<li>Fecha de nacimiento: {{gato.fecha_nacimiento}}</li>
{% endblock contenido %}

inicio/templates/inicio/eliminar_gato.html
{% extends 'base.html' %}

{% block title_head %}
<title>Eliminar Gato</title>
{% endblock title_head %}

{% block h1_header %}
Eliminar Gato {{gato.nombre}}
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'inicio:eliminar_gato' gato.id%} method="post">
    {% csrf_token %}
    <p>Va a eliminar a {{gato}}</p>
    <button>Confirmar</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/gatos.html
{% extends 'base.html' %}

{% block title_head %}
<title>Gatos</title>
{% endblock title_head %}

{% block h1_header %}
Gatos
{% endblock h1_header %}

{% block contenido %}
<button>
    <a class="navbar-brand" href={% url 'inicio:crear_gato' %}>Crear gato</a>
</button>

<form action={% url 'inicio:gatos' %}>
    {{formulario}}
    <button>Busqueda</button>
</form>

{% if lista_gatos %}
{% for gato in lista_gatos %}
<li>
    <a href={% url 'inicio:detalle_gato' gato.id %}>{{gato}}</a>
    <button>
        <a class="navbar-brand" href={% url 'inicio:modificar_gato' gato.id %}>Modificar</a>
    </button>
    <button>
        <a class="navbar-brand" href={% url 'inicio:eliminar_gato' gato.id %}>Eliminar</a>
    </button>
</li>
{% endfor %}
{% else %}
<p>No se encontraron gatos.</p>
{% endif %}

{% endblock contenido %}

inicio/templates/inicio/inicio.html
{% extends 'base.html' %}

{% block title_head %}
<title>Inicio</title>
{% endblock title_head %}

{% block h1_header %}
Bienvenidos a mi pagina
{% endblock h1_header %}

{% block contenido %}
<p>
    Esta es la pagina desarrollada para el after.
</p>
{% endblock contenido %}

inicio/templates/inicio/modificar_gato.html
{% extends 'base.html' %}

{% block title_head %}
<title>Modificar Gato</title>
{% endblock title_head %}

{% block h1_header %}
Modificar Gato {{gato.nombre}}
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'inicio:modificar_gato' gato.id %} method="post">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <button>Modificar</button>
</form>
{% endblock contenido %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title_head %}
        <title>Landing Page - Start Bootstrap Theme</title>
        {% endblock title_head %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href={% url 'inicio:inicio' %}>Inicio</a>
                <a class="navbar-brand" href={% url 'inicio:gatos' %}>Gatos</a>
                <a class="btn btn-primary" href="#">Iniciar sesion</a>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">
                                {% block h1_header %}
                                {% endblock h1_header %}
                            </h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% block contenido %}
        {% endblock contenido %}
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static 'js/scripts.js' %}></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>